<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestorsOnTour.Domain\TestorsOnTour.Domain.csproj" />
    <ProjectReference Include="..\TestorsOnTour.Persistence\TestorsOnTour.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\" />
    <Folder Include="Hikes\" />
    <Folder Include="Hikes\Commands\" />
    <Folder Include="Hikes\Queries\" />
  </ItemGroup>

</Project>
